export const SET_NAME = "SET_NAME";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const ADD_PURCHASE = "ADD_PURCHASE";
export const REMOVE_PURCHASE = "REMOVE_PURCHASE";
export const SET_PURCHASE_PLACE = "SET_PURCHASE_PLACE";
export const SET_PURCHASE_DATE = "SET_PURCHASE_DATE";
export const SET_PURCHASE_DESCRIPTION = "SET_PURCHASE_DESCRIPTION";
export const SET_PURCHASE_SUM = "SET_PURCHASE_SUM";
